---
services:
  proxy:
    image: nginx:1.27
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      # Mount the nginx folder with the configuration
      - ./nginx:/etc/nginx:ro
      # Static files for django
      - django-static-volume:/static/django-static:ro
      # Mount the nginx log folder
      - ./log:/var/log/winearth:rw
      # Mount the letsencrypt certificates
      - ./certbot/conf:/etc/letsencrypt:ro
      # Mount the certbot renewal wwwroot
      - ./certbot/www:/var/www/certbot:ro
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      winearth-api-server:
        condition: service_started
      winearth-webui:
        condition: service_started

  winearth-api-server:
    image: ghcr.io/windows-on-earth/winearth-api:0.2.1
    restart: always
    environment:
      - DEBUG=False
    volumes:
      - django-static-volume:/django/static

  winearth-webui:
    image: ghcr.io/windows-on-earth/winearth-webui:1.1.3
    restart: "no"
    depends_on:
      winearth-api-server:
        condition: service_started

  certbot:
    image: certbot/certbot:v2.11.0
    restart: always
    volumes:
      # Mount the letsencrypt certificates
      - ./certbot/conf:/etc/letsencrypt
      # Mount the certbot renewal wwwroot
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot --webroot-path /var/www/certbot/; sleep 12h & wait $${!}; done;'"

volumes:
  django-static-volume:
